# Generated by Django 2.0.6 on 2018-06-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_endpoint', models.CharField(max_length=512)),
                ('source_bucket', models.CharField(blank=True, max_length=255)),
                ('source_file_name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountingRequest',
        ),
    ]
