# Generated by Django 2.0.6 on 2018-06-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_countrequest_source_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrequest',
            name='bus_stop_congestion_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
